from pathlib import Path
import json

from PIL import Image, ImageEnhance


ROOT = Path(__file__).resolve().parents[1]
SPRITES = ROOT / "public" / "assets" / "sprites"
ANIMATION_MODULE = ROOT / "src" / "data" / "spriteAnimations.js"
DIRECTIONS = ["front", "back", "left", "right"]
WALK_OFFSETS = {
    "front": [(0, 0), (-1, -1), (1, 0)],
    "back": [(0, 0), (1, -1), (-1, 0)],
    "left": [(0, 0), (-2, -1), (-1, 0)],
    "right": [(0, 0), (2, -1), (1, 0)],
}
ATTACK_OFFSETS = {
    "front": (0, 4),
    "back": (0, -4),
    "left": (-4, 0),
    "right": (4, 0),
}


def has_action_set(unit_dir):
    return all(
        (unit_dir / f"{action}-{direction}.png").exists()
        for action in ("walk", "attack")
        for direction in DIRECTIONS
    )


def animation_units():
    return [
        unit_dir.name
        for unit_dir in sorted(SPRITES.iterdir())
        if unit_dir.is_dir() and has_action_set(unit_dir)
    ]


def shifted(image, offset, brighten=1.0):
    source = image.convert("RGBA")
    if brighten != 1.0:
        alpha = source.getchannel("A")
        rgb = Image.new("RGBA", source.size, (0, 0, 0, 0))
        rgb.alpha_composite(source)
        rgb = ImageEnhance.Brightness(rgb).enhance(brighten)
        rgb.putalpha(alpha)
        source = rgb
    canvas = Image.new("RGBA", source.size, (0, 0, 0, 0))
    canvas.alpha_composite(source, offset)
    return canvas


def write_walk_frames(unit_dir, direction):
    src = unit_dir / f"walk-{direction}.png"
    if not src.exists():
        return 0
    image = Image.open(src)
    count = 0
    for index, offset in enumerate(WALK_OFFSETS[direction]):
        shifted(image, offset).save(unit_dir / f"walk-{direction}-{index}.png")
        count += 1
    return count


def write_attack_frames(unit_dir, direction):
    src = unit_dir / f"attack-{direction}.png"
    if not src.exists():
        return 0
    image = Image.open(src)
    shifted(image, (0, 0)).save(unit_dir / f"attack-{direction}-0.png")
    shifted(image, ATTACK_OFFSETS[direction], brighten=1.18).save(unit_dir / f"attack-{direction}-1.png")
    return 2


def existing_frame_paths(unit_id, action, direction):
    paths = []
    index = 0
    while True:
        path = SPRITES / unit_id / f"{action}-{direction}-{index}.png"
        if not path.exists():
            break
        paths.append(f"assets/sprites/{unit_id}/{action}-{direction}-{index}.png")
        index += 1
    return paths


def animation_manifest():
    manifest = {}
    for unit_dir in sorted(SPRITES.iterdir()):
        if not unit_dir.is_dir():
            continue
        unit = {}
        for action in ("walk", "attack"):
            action_map = {}
            for direction in DIRECTIONS:
                frames = existing_frame_paths(unit_dir.name, action, direction)
                if len(frames) >= 2:
                    action_map[direction] = frames
            if action_map:
                unit[action] = action_map
        if unit:
            manifest[unit_dir.name] = unit
    return manifest


def write_animation_module():
    manifest = animation_manifest()
    body = json.dumps(manifest, indent=2, ensure_ascii=False)
    ANIMATION_MODULE.write_text(
        "// Generated by scripts/make_micro_animation_frames.py. Do not edit by hand.\n\n"
        f"export const spriteAnimations = {body};\n",
        encoding="utf-8",
    )
    return len(manifest)


def main():
    written = 0
    units = animation_units()
    for unit_id in units:
        unit_dir = SPRITES / unit_id
        for direction in DIRECTIONS:
            written += write_walk_frames(unit_dir, direction)
            written += write_attack_frames(unit_dir, direction)
    connected = write_animation_module()
    print(f"wrote {written} micro animation frames for {len(units)} units")
    print(f"connected {connected} animated sprite folders in {ANIMATION_MODULE}")


if __name__ == "__main__":
    main()
